# -*- coding: utf-8 -*-
"""smolvla_train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qK-ZiJtul_Hjzm9oE3GKYXyOvhvKqQ8R
"""

# ── Cell 1: Check GPU ─────────────────────────────────────────
!nvidia-smi
import torch
print(f'CUDA available: {torch.cuda.is_available()}')
if torch.cuda.is_available():
    print(f'GPU: {torch.cuda.get_device_name(0)}')
    print(f'VRAM: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB')

!pip install -q "lerobot[smolvla,libero]"
!pip install -q wandb

# Set MuJoCo rendering for headless Colab (CRITICAL for eval)
import os
os.environ["MUJOCO_GL"] = "egl"

# Verify lerobot installed correctly
import lerobot
print(f"LeRobot version: {lerobot.__version__}")

"""No we will do the huggin face and wandb login"""

from huggingface_hub import login as hf_login
hf_login()  # Paste HF token — needs WRITE access for uploading checkpoints

import wandb
wandb.login()  # Paste W&B token from wandb.ai/authorize

print("✅ Logged in to HuggingFace and W&B")

# ── Cell 4: Sanity Run (500 steps, minimal eval) ───────────────────────────
# PURPOSE: Verify everything works before committing to a long run.
# - 500 training steps (~4 min on A100)
# - Eval only at step 500, on just 2 tasks, 2 episodes each
# - Total time: ~10-15 min including eval
#
# WHAT TO CHECK:
# - Loss should decrease from ~0.3 to ~0.15
# - Grad norm should stay < 5
# - Eval should complete without errors
# - You should see success_rate metrics (even if 0%)

!rm -rf ./outputs/sanity-check

!MUJOCO_GL=egl lerobot-train \
  --policy.path=lerobot/smolvla_base \
  --policy.repo_id=goelshivam1210/smolvla-sanity-check \
  --dataset.repo_id=HuggingFaceVLA/libero \
  --env.type=libero \
  --env.task=libero_spatial \
  --env.task_ids='[0,1]' \
  --rename_map='{"observation.images.image": "observation.images.camera1", "observation.images.image2": "observation.images.camera2"}' \
  --output_dir=./outputs/sanity-check \
  --job_name=smolvla-sanity-check \
  --steps=500 \
  --batch_size=32 \
  --optimizer.lr=2e-4 \
  --eval_freq=500 \
  --save_freq=500 \
  --eval.batch_size=1 \
  --eval.n_episodes=2 \
  --policy.device=cuda \
  --policy.use_amp=true \
  --wandb.enable=true \
  --wandb.project=smolvla-libero

# ── Cell 5: Check Sanity Run Results ────────────────────────────────────────
# If Cell 4 completed successfully, check the output
!ls -la ./outputs/sanity-check/checkpoints/
print("\n✅ Sanity check passed! Ready for full training runs.")

!rm -rf /root/.cache/huggingface/datasets/
!rm -rf /root/.cache/huggingface/hub/datasets--HuggingFaceVLA--libero/
!rm -rf ./outputs/
!df -h /

import os
os.environ["HF_HUB_ENABLE_HF_TRANSFER"] = "1"

!pip install -q hf_transfer

from huggingface_hub import snapshot_download
snapshot_download(
    repo_id="HuggingFaceVLA/libero",
    repo_type="dataset",
    allow_patterns=["*.parquet", "*.json", "*.jsonl"],
    max_workers=1,
)
print("✅ Dataset downloaded")

!rm -rf ./outputs/sanity-check

!MUJOCO_GL=egl lerobot-train \
  --policy.path=lerobot/smolvla_base \
  --policy.repo_id=goelshivam1210/smolvla-sanity-check \
  --dataset.repo_id=HuggingFaceVLA/libero \
  --env.type=libero \
  --env.task=libero_spatial \
  --env.task_ids='[0,1]' \
  --rename_map='{"observation.images.image": "observation.images.camera1", "observation.images.image2": "observation.images.camera2"}' \
  --output_dir=./outputs/sanity-check \
  --job_name=smolvla-sanity-check \
  --steps=500 \
  --batch_size=32 \
  --optimizer.lr=2e-4 \
  --eval_freq=500 \
  --save_freq=500 \
  --eval.batch_size=1 \
  --eval.n_episodes=2 \
  --policy.device=cuda \
  --policy.use_amp=true \
  --wandb.enable=true \
  --wandb.project=smolvla-libero

!rm -rf ./outputs/sanity-check
!df -h /

!nvidia-smi
!df -h /

!rm -rf ./outputs/
!rm -rf /root/.cache/huggingface/hub/models--lerobot--smolvla_base/blobs/
!df -h /

!du -h --max-depth=2 /root/.cache/huggingface/ | sort -rh | head -20

!rm -rf /root/.cache/huggingface/datasets/
!rm -rf /root/.cache/huggingface/hub/datasets--HuggingFaceVLA--libero/
!df -h /

!rm -rf ./outputs/smolvla-libero-lora-r32

!MUJOCO_GL=egl lerobot-train \
  --policy.path=lerobot/smolvla_base \
  --policy.repo_id=goelshivam1210/smolvla-libero-lora-r32 \
  --dataset.repo_id=HuggingFaceVLA/libero \
  --env.type=libero \
  --env.task=libero_spatial \
  --env.task_ids='[0,1,2,3,4]' \
  --rename_map='{"observation.images.image": "observation.images.camera1", "observation.images.image2": "observation.images.camera2"}' \
  --output_dir=./outputs/smolvla-libero-lora-r32 \
  --job_name=smolvla-libero-lora-r32 \
  --steps=5000 \
  --batch_size=32 \
  --optimizer.lr=2e-4 \
  --peft.method_type=LORA \
  --peft.r=32 \
  --eval_freq=2500 \
  --save_freq=2500 \
  --eval.batch_size=1 \
  --eval.n_episodes=3 \
  --policy.device=cuda \
  --policy.use_amp=true \
  --wandb.enable=true \
  --wandb.project=smolvla-libero

!nvidia-smi
!ls ./outputs/smolvla-libero-lora-r32/checkpoints/

!rm -rf ./outputs/smolvla-libero-lora-r8

!MUJOCO_GL=egl lerobot-train \
  --policy.path=lerobot/smolvla_base \
  --policy.repo_id=goelshivam1210/smolvla-libero-lora-r8 \
  --dataset.repo_id=HuggingFaceVLA/libero \
  --env.type=libero \
  --env.task=libero_spatial \
  --rename_map='{"observation.images.image": "observation.images.camera1", "observation.images.image2": "observation.images.camera2"}' \
  --output_dir=./outputs/smolvla-libero-lora-r8 \
  --job_name=smolvla-libero-lora-r8 \
  --steps=5000 \
  --batch_size=32 \
  --optimizer.lr=2e-4 \
  --peft.method_type=LORA \
  --peft.r=8 \
  --eval_freq=999999 \
  --save_freq=2500 \
  --policy.device=cuda \
  --policy.use_amp=true \
  --wandb.enable=true \
  --wandb.project=smolvla-libero

!rm -rf ./outputs/smolvla-libero-lora-r8

!MUJOCO_GL=egl lerobot-train \
  --policy.path=lerobot/smolvla_base \
  --policy.repo_id=goelshivam1210/smolvla-libero-lora-r8 \
  --dataset.repo_id=HuggingFaceVLA/libero \
  --env.type=libero \
  --env.task=libero_spatial \
  --env.task_ids='[0]' \
  --rename_map='{"observation.images.image": "observation.images.camera1", "observation.images.image2": "observation.images.camera2"}' \
  --output_dir=./outputs/smolvla-libero-lora-r8 \
  --job_name=smolvla-libero-lora-r8 \
  --steps=5000 \
  --batch_size=32 \
  --optimizer.lr=2e-4 \
  --peft.method_type=LORA \
  --peft.r=8 \
  --eval_freq=999999 \
  --save_freq=2500 \
  --policy.device=cuda \
  --policy.use_amp=true \
  --wandb.enable=true \
  --wandb.project=smolvla-libero

!MUJOCO_GL=egl lerobot-eval \
  --policy.path=./outputs/smolvla-libero-lora-r32/checkpoints/last/pretrained_model \
  --env.type=libero \
  --env.task=libero_spatial \
  --env.task_ids='[0]' \
  --eval.batch_size=1 \
  --eval.n_episodes=5 \
  --output_dir=./outputs/eval-id-r32

!MUJOCO_GL=egl lerobot-eval \
  --policy.path=./outputs/smolvla-libero-lora-r32/checkpoints/last/pretrained_model \
  --env.type=libero \
  --env.task=libero_spatial \
  --env.task_ids='[0]' \
  --eval.batch_size=1 \
  --eval.n_episodes=5 \
  --rename_map='{"observation.images.image": "observation.images.camera1", "observation.images.image2": "observation.images.camera2"}' \
  --output_dir=./outputs/eval-id-r32

!MUJOCO_GL=egl lerobot-eval \
  --policy.path=./outputs/smolvla-libero-lora-r8/checkpoints/last/pretrained_model \
  --env.type=libero \
  --env.task=libero_spatial \
  --env.task_ids='[0]' \
  --eval.batch_size=1 \
  --eval.n_episodes=5 \
  --rename_map='{"observation.images.image": "observation.images.camera1", "observation.images.image2": "observation.images.camera2"}' \
  --output_dir=./outputs/eval-id-r8

!ls -la ./outputs/eval-id-r8/videos/

!ls ./outputs/eval-id-r8/videos/libero_spatial_0/

!cat ./outputs/eval-id-r8/eval_info.json 2>/dev/null || echo "No eval_info.json, check logs"

import json

# Fix n_action_steps for both checkpoints
for run in ["smolvla-libero-lora-r32", "smolvla-libero-lora-r8"]:
    path = f"./outputs/{run}/checkpoints/last/pretrained_model/config.json"
    try:
        with open(path, "r") as f:
            config = json.load(f)
        config["n_action_steps"] = 50
        with open(path, "w") as f:
            json.dump(config, f, indent=2)
        print(f"✅ Fixed n_action_steps for {run}")
    except Exception as e:
        print(f"⚠️ {run}: {e}")

# Upload both checkpoints to HuggingFace
from huggingface_hub import HfApi
api = HfApi()

for run, repo in [
    ("smolvla-libero-lora-r32", "goelshivam1210/smolvla-libero-lora-r32"),
    ("smolvla-libero-lora-r8", "goelshivam1210/smolvla-libero-lora-r8"),
]:
    try:
        api.upload_folder(
            folder_path=f"./outputs/{run}/checkpoints/last/pretrained_model",
            repo_id=repo,
            repo_type="model"
        )
        print(f"✅ Uploaded {repo}")
    except Exception as e:
        print(f"⚠️ Upload {repo}: {e}")

print("\n🎉 Done! Checkpoints on HuggingFace.")

!zip -r /content/all_results.zip ./outputs/eval-id-r32/videos/ ./outputs/eval-id-r8/videos/ ./outputs/smolvla-libero-lora-r32/checkpoints/last/pretrained_model/ ./outputs/smolvla-libero-lora-r8/checkpoints/last/pretrained_model/

!rm -rf ./outputs/smolvla-libero-extended

!MUJOCO_GL=egl lerobot-train \
  --policy.path=HuggingFaceVLA/smolvla_libero \
  --policy.repo_id=goelshivam1210/smolvla-libero-extended \
  --dataset.repo_id=HuggingFaceVLA/libero \
  --env.type=libero \
  --env.task=libero_spatial \
  --env.task_ids='[0]' \
  --output_dir=./outputs/smolvla-libero-extended \
  --job_name=smolvla-libero-extended \
  --steps=20000 \
  --batch_size=32 \
  --optimizer.lr=2e-4 \
  --peft.method_type=LORA \
  --peft.r=32 \
  --eval_freq=5000 \
  --save_freq=5000 \
  --eval.batch_size=1 \
  --eval.n_episodes=5 \
  --policy.device=cuda \
  --policy.use_amp=true \
  --wandb.enable=true \
  --wandb.project=smolvla-libero